package watch.entity;
// Generated Nov 5, 2020 5:22:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;

/**
 * Admins generated by hbm2java
 */
public class Admins  implements java.io.Serializable {


     private String nameAdmin;
     private String passAdmin;

    public Admins() {
    }

	
    public Admins(String nameAdmin) {
        this.nameAdmin = nameAdmin;
    }
    public Admins(String nameAdmin, String passAdmin) {
       this.nameAdmin = nameAdmin;
       this.passAdmin = passAdmin;
    }
   
    public String getNameAdmin() {
        return this.nameAdmin;
    }
    
    public void setNameAdmin(String nameAdmin) {
        this.nameAdmin = nameAdmin;
    }
    public String getPassAdmin() {
        return this.passAdmin;
    }
    
    public void setPassAdmin(String passAdmin) {
        this.passAdmin = passAdmin;
    }




}


