package watch.entity;
// Generated Nov 5, 2020 5:22:15 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int orderId;
     private WebUser webUser;
     private String name;
     private Date created;
     private Boolean orderStatus;
     private String phone;
     private String mail;
     private Float totalAmount;
     private String addresss;
     private Set orderDetails = new HashSet(0);

    public Orders() {
    }

	
    public Orders(int orderId) {
        this.orderId = orderId;
    }
    public Orders(int orderId, WebUser webUser, String name, Date created, Boolean orderStatus, String phone, String mail, Float totalAmount, String addresss, Set orderDetails) {
       this.orderId = orderId;
       this.webUser = webUser;
       this.name = name;
       this.created = created;
       this.orderStatus = orderStatus;
       this.phone = phone;
       this.mail = mail;
       this.totalAmount = totalAmount;
       this.addresss = addresss;
       this.orderDetails = orderDetails;
    }
   
    public int getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(int orderId) {
        this.orderId = orderId;
    }
    public WebUser getWebUser() {
        return this.webUser;
    }
    
    public void setWebUser(WebUser webUser) {
        this.webUser = webUser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getCreated() {
        return this.created;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    public Boolean getOrderStatus() {
        return this.orderStatus;
    }
    
    public void setOrderStatus(Boolean orderStatus) {
        this.orderStatus = orderStatus;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public Float getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Float totalAmount) {
        this.totalAmount = totalAmount;
    }
    public String getAddresss() {
        return this.addresss;
    }
    
    public void setAddresss(String addresss) {
        this.addresss = addresss;
    }
    public Set getOrderDetails() {
        return this.orderDetails;
    }
    
    public void setOrderDetails(Set orderDetails) {
        this.orderDetails = orderDetails;
    }




}


